# .github/workflows/birthday-check.yml
name: 🎂 Sistema de Aniversários PM - Verificação Automática

on:
  schedule:
    # Executa todo dia às 9h (horário UTC = 6h Brasília)
    - cron: '0 12 * * *'  # 12h UTC = 9h Brasília
  
  # Permite execução manual
  workflow_dispatch:
  
  # Para testes, executa a cada push
  push:
    branches: [ main ]
    paths: [ 'scripts/**' ]

jobs:
  verificar-aniversarios:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout do código
      uses: actions/checkout@v4
    
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: 📦 Instalar dependências
      run: npm install
    
    - name: 🎖️ Executar verificação PM
      env:
        # Variáveis de ambiente seguras (configurar no GitHub)
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
        TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
        NOTIFICATION_TIMING: ${{ secrets.NOTIFICATION_TIMING }}
        NOTIFICATION_TIME: ${{ secrets.NOTIFICATION_TIME }}
      run: node scripts/check-birthdays.js
    
    - name: 📋 Salvar logs da execução
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs-${{ github.run_number }}
        path: logs/
        retention-days: 30
    
    - name: 📱 Notificar resultado via Webhook (opcional)
      if: failure()
      run: |
        curl -X POST "${{ secrets.WEBHOOK_URL }}" \
        -H "Content-Type: application/json" \
        -d '{"text":"❌ Falha na verificação de aniversários PM - Run #${{ github.run_number }}"}'
